#! /usr/bin/env ruby

#
# This is an inode agent which monitors
# disk INode usage
#

require "rubygems"
require "bundler/setup"
require "newrelic_plugin"

module INodeAgent
  class Agent < NewRelic::Plugin::Agent::Base

    agent_guid "com.tsp.inodes_mon"
    agent_version "1.0.0"
    agent_config_options :hostname
    agent_human_labels("Inode Agent") { "#{hostname}" }

    def poll_cycle        start = `df -i`.gsub('map ', 'map.')
        start = start.gsub('Mounted on', 'Mounted_On')
        result = {}
        resultpct = []
        disks = start.lines
        headers = disks.to_a.shift()
        headers = headers.split(/[ ]{1,}/)
        disks.each { |line|
            line = line.split(/[ ]{1,}/)

            mountedFrom = line[0].strip().gsub(/^\/|\/$/, '')
            result[mountedFrom] = {}
            i = 0
            headers.each { |header|
                header = header.gsub(/^%/, 'pct.').gsub(/%$/, '.pct').gsub(/%/, '.pct.').strip()
                #puts "header: #{header}"
                result[mountedFrom][header] = line[i].strip().gsub('%', '').strip().gsub(/^\/|\/$/, '')
                #puts "result: #{result}"
                if header == "IUse.pct"
                  resultpct.push(line[i].strip().gsub('%', '').strip().gsub(/^\/|\/$/, '').to_i)
                end
                #puts "pct: #{resultpct}"
                i += 1
            }
        }
        inodesmax = resultpct.max
        puts "Reporting max inodes usage for 'iNodes/max/#{inodesmax}"
        report_metric("iNodes/maxpctusage", "Value", inodesmax )
        result.each { | disk, metric |
            metric.each { | k, v|
                report_metric("iNodes/#{disk}/#{k}",  "#{k}", v)
                puts "Reporting usage for 'iNodes/#{disk}/#{k}' as #{v}"
            }
        }


    end

  end

  NewRelic::Plugin::Setup.install_agent :inode, INodeAgent

  NewRelic::Plugin::Run.setup_and_run

end
